language: r
sudo: false
cache: packages
r_packages:
- knitr
- drat
- covr
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: dfkRnOHxg9r6t3sZVMsneWJZ07lOY5geaqBs9O+CTqTBw4JUUtOFnF8lwvjmUJrLNZWW/6xoq9lOrFChueXrwtWZwzbyCZCY6o/cmLX/3+vNp8MkajE0v6R7yKwDjlSuCsMjjGWH0xWCZ+nyVNam9dDgow6xuzkxKjHbp7I3vq8=
